version: '3'
services:
  mysql:
    build: mysql/.
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=123456
  wildfly:
    build: wildfly/.
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - mysql:db